/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaInicial;

import DAO.LigacaoDAO;
import DTO.LigacaoDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jamile
 */
public class Início extends javax.swing.JFrame {


    /**
     * Creates new form Início
     */
    public Início() {
        initComponents();
        ConsultarExtintor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Início = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txttipos = new javax.swing.JComboBox<>();
        Cadastro = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Alterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOrdem = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtLocalizaçao = new javax.swing.JTextField();
        txtValidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_extin = new javax.swing.JTable();
        Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setBackground(new java.awt.Color(255, 255, 204));

        Início.setBackground(new java.awt.Color(255, 255, 204));
        Início.setMinimumSize(new java.awt.Dimension(500, 300));
        Início.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Tipo de Extintor:");
        Início.add(jLabel1);
        jLabel1.setBounds(10, 80, 140, 14);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("ESCOLHA DO EXTINTOR");
        Início.add(jLabel2);
        jLabel2.setBounds(100, 10, 330, 35);

        txttipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "ÁGUA", "CO² 6KG", "PQS 4KG", "PQS 6KG", "PQS 12KG", "CARRETA" }));
        txttipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttiposActionPerformed(evt);
            }
        });
        Início.add(txttipos);
        txttipos.setBounds(100, 80, 86, 22);

        Cadastro.setText("Cadastrar");
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });
        Início.add(Cadastro);
        Cadastro.setBounds(10, 270, 90, 22);

        Consultar.setText("Atualizar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        Início.add(Consultar);
        Consultar.setBounds(110, 270, 76, 22);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        Início.add(btnExcluir);
        btnExcluir.setBounds(310, 270, 72, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/extintor-de-incendio (6).png"))); // NOI18N
        Início.add(jLabel3);
        jLabel3.setBounds(230, 50, 260, 200);

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        Início.add(Alterar);
        Alterar.setBounds(210, 270, 72, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Validade:");
        Início.add(jLabel4);
        jLabel4.setBounds(10, 140, 60, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Localização:");
        Início.add(jLabel5);
        jLabel5.setBounds(10, 170, 80, 14);

        jLabel6.setText("Ordem:");
        Início.add(jLabel6);
        jLabel6.setBounds(10, 200, 40, 16);
        Início.add(txtOrdem);
        txtOrdem.setBounds(100, 200, 80, 22);

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });
        Início.add(txtnumero);
        txtnumero.setBounds(100, 110, 80, 22);

        txtLocalizaçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocalizaçaoActionPerformed(evt);
            }
        });
        Início.add(txtLocalizaçao);
        txtLocalizaçao.setBounds(100, 170, 80, 22);

        txtValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeActionPerformed(evt);
            }
        });
        Início.add(txtValidade);
        txtValidade.setBounds(100, 140, 80, 22);

        jLabel7.setText("Número:");
        Início.add(jLabel7);
        jLabel7.setBounds(10, 110, 50, 16);

        tbl_extin.setAutoCreateRowSorter(true);
        tbl_extin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Número", "Validade", "Localização", "Ordem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_extin.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_extin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_extinAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbl_extin);

        Início.add(jScrollPane1);
        jScrollPane1.setBounds(0, 312, 500, 200);

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        Início.add(Limpar);
        Limpar.setBounds(410, 270, 70, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Início, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Início, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttiposActionPerformed

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed
        try {
            Cadastrar();
        } catch (SQLException ex) {
            Logger.getLogger(Início.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConsultarExtintor();
    }//GEN-LAST:event_CadastroActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        try {          
            Alterar();
        } catch (SQLException ex) {
            Logger.getLogger(Início.class.getName()).log(Level.SEVERE, null, ex);
        } ConsultarExtintor();
    }//GEN-LAST:event_AlterarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
             ConsultarExtintor();
                
    }//GEN-LAST:event_ConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            ExcluirExtintor();
        } catch (SQLException ex) {
            Logger.getLogger(Início.class.getName()).log(Level.SEVERE, null, ex);
        } ConsultarExtintor();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tbl_extinAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_extinAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_extinAncestorAdded

    private void txtLocalizaçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocalizaçaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocalizaçaoActionPerformed

    private void txtValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        LimparDados();
    }//GEN-LAST:event_LimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Início.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Início.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Início.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Início.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Início().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Cadastro;
    private javax.swing.JButton Consultar;
    private javax.swing.JPanel Início;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_extin;
    private javax.swing.JTextField txtLocalizaçao;
    private javax.swing.JTextField txtOrdem;
    private javax.swing.JTextField txtValidade;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JComboBox<String> txttipos;
    // End of variables declaration//GEN-END:variables


private void Cadastrar() throws SQLException {//Método para Cadastrar o registro
    
        String tipo; //declaraçao das variáveis
        String Localização;
        String validade;
        Integer id_ordem, numero;
        
        tipo = (String) txttipos.getSelectedItem();//pegando os dados do combobox com o getselectedItem
        Localização = txtLocalizaçao.getText();
        id_ordem = Integer.parseInt(txtOrdem.getText()); //dados integer sendo convertidos para String
        validade = txtValidade.getText();
        numero = Integer.parseInt(txtnumero.getText());
        
        LigacaoDTO ObjLigacaoDTO = new LigacaoDTO();
        
        ObjLigacaoDTO.setNumero(numero);
        ObjLigacaoDTO.setLocalizaçao(Localização);
        ObjLigacaoDTO.setId_Ordem(id_ordem);
        ObjLigacaoDTO.setValidade(validade);
        ObjLigacaoDTO.setTipo(tipo);
        
        LigacaoDAO  ObjLigacaoDAO = new LigacaoDAO();
        ObjLigacaoDAO.CadastrarDAO(ObjLigacaoDTO);
               
    }

private void Alterar() throws SQLException   { //Método para alterar o registro
        
        String tipo;
        String Localização;
        String validade;
        Integer id_ordem, numero;
        
        tipo = (String) txttipos.getSelectedItem();
        numero = Integer.parseInt(txtnumero.getText());
        Localização = txtLocalizaçao.getText();        
        validade = txtValidade.getText();
        id_ordem = Integer.parseInt(txtOrdem.getText());
        
        LigacaoDTO ObjLigacaoDTO = new LigacaoDTO(); //Objeto vindo do pacote DTO
        
        ObjLigacaoDTO.setTipo(tipo);
        ObjLigacaoDTO.setNumero(numero);
        ObjLigacaoDTO.setLocalizaçao(Localização);
        ObjLigacaoDTO.setValidade(validade);
        ObjLigacaoDTO.setId_Ordem(id_ordem);
        
        
        LigacaoDAO  ObjLigacaoDAO = new LigacaoDAO();
        ObjLigacaoDAO.Alterar(ObjLigacaoDTO);
       
        }

public void ExcluirExtintor() throws SQLException{//Método para Excluir o registro

            int id_ordem;    
         id_ordem = Integer.parseInt(txtOrdem.getText());
         
         LigacaoDTO objLigacaoDTO = new LigacaoDTO();
         objLigacaoDTO.setId_Ordem(id_ordem);
                  
         LigacaoDAO objLigacaoDAO = new LigacaoDAO();
         objLigacaoDAO.Excluir(objLigacaoDTO);

    }


        private void ConsultarExtintor() {//Método para atualizar a lista após alteraçoes

        try {
                        
            LigacaoDAO objLigacaoDAO = new LigacaoDAO();
            
            DefaultTableModel model = (DefaultTableModel) tbl_extin.getModel(); //Parte criada para inserir uma table
            model.setNumRows(0);//método pra inserir novas linhas após a inserção dos valores
           
            ArrayList<LigacaoDTO> lista = objLigacaoDAO.ConsultarDAO(); //criação do array pra incrementar os dados na table
                    
            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getTipo(), //o get para pegar os dados
                    lista.get(num).getNumero(),
                    lista.get(num).getValidade(),
                    lista.get(num).getLocalizaçao(),
                    lista.get(num).getId_Ordem(),
                        
                        
                                                       
                });      
            }               

         } catch (SQLException erro) {

            JOptionPane.showMessageDialog(null, "consultar extintor" + erro);
                 }
        
        } 
 
 private void LimparDados(){
        
        
        txtLocalizaçao.setText("");
        txtnumero.getText();
        txtOrdem.getText();
        txtValidade.setText("");
        
        
        } 
    
    
    
}
